language: python
python:
    - 2.7
    - 3.3
    - pypy

before_install:
    - pip install --quiet coverage

install:
    - python setup.py install

script:
    - make test
    - source env/activate && coverage run --omit='*/site-packages/*,*/distutils/*' ./test/test.py
    - source env/activate && coverage report --show-missing

after_success:
    - pip install --quiet coveralls
    - coveralls
